import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import TransitionEffect from "@/components/TransitionEffect";

export default function Home() {
  return (
    <>
      <Head>
        <title>Portafolio-Next.Js</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image
                src={profilePic}
                alt="CodeBucks"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Transformando visiones en realidad mediante código y diseño."
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl sm:!text-3xl"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                Como desarrollador full-stack, me apasiona transformar ideas
                creativas en aplicaciones web innovadoras y atractivas. En mis
                proyectos recientes, he utilizado mi experiencia en tecnologías
                como React.js y desarrollo web para crear soluciones escalables
                y eficientes. Si estás buscando un desarrollador web que pueda
                transformar tu idea en una aplicación web increíble, ¡no dudes
                en contactarme!
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/dummy.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold
                  hover:bg-light hover:text-dark border-2 border-solid border-transparent 
                  hover:border-dark transition duration-300 ease-in-out
                  dark:bg-light dark:text-dark dark:hover:bg-dark dark:hover:text-light dark:hover:border-light
                  md:p-2 md:px-4 md:text-base
                "
                  download={true}
                >
                  Resumen PDF
                  <LinkArrow className={"!w-5 ml-1"} />
                </Link>
                <Link
                  href="kevin.munoz0995@gmail.com"
                  target={"_blank"}
                  className="
                ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base
                "
                >
                  Contacto
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute right-8 bottom-8 inline-block w-24 md:hidden">
          <Image src={lightBulb} alt="vinke" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
